export const REQUEST_TRANSFER_TOKEN = "REQUEST_TRANSFER_TOKEN";
export const RECEIVE_TRANSFER_TOKEN_ACK = "RECEIVE_TRANSFER_TOKEN_ACK";

export const REQUEST_MERKLE_ROOT = "REQUEST_MERKLE_ROOT"
export const RECEIVE_MERKLE_ROOT = "RECEIVE_MERKLE_ROOT"

export const REQUEST_MERKLE_PROOFS = "REQUEST_MERKLE_PROOFS"
export const RECEIVE_MERKLE_PROOFS = "RECEIVE_MERKLE_PROOFS"

export const REQUEST_VALIDATE_MERKLE_PROOF = "REQUEST_MERKLE_PROOF"
export const RECEIVE_VALIDATE_MERKLE_PROOF = "RECEIVE_MERKLE_PROOF"